language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_script:
  - /bin/bash ./.travis.sh

install:
  - pip install -r requirements.txt
  - pip install -r requirements.testing.txt
  - pip install .

script:
  - nosetests --with-coverage --cover-package=pyley

after_success:
  - coveralls
